### PR TITLE
Brain issue fix

### PR DESCRIPTION
**Pull request by TheSainEyereg**
<details>
<summary>Please merge</summary>
Or Guido van Rossum will die in pain
</details>

### CODE REVIEW

**Comment by Eld3rly** [comment]
Elderly was here

**Comment by Eld3rly** [comment]
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here

**Comment by Eld3rly** [comment]
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here

**Comment by Eld3rly** [comment]
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here

**Comment by Eld3rly** [comment]
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here

**Comment by Eld3rly** [comment]
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here

**Comment by Eld3rly** [comment]
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here
Elderly was here

**Comment by slpkbt** [comment]
гений фиксов апзхзапхзапх

**Comment by Vazgen005** [comment]
> гений фиксов апзхзапхзапх

He just replace full code

**Pull request closed without merging**
